### ISSUE TITLE
Security / Test / Mixins / Meta

### ISSUE THREAD

**Issue by Fifciu** [vue-wordpress/core#123]
If **metaSource** aka meta's key is not provided:
- [ ] It returns an object, contains meta with charset
Otherwise:
- [ ] It returns a proper title
- [ ] It returns a proper **description** with escape HTML chars
- [ ] It sets a proper og:description
- [ ] It sets a proper og:type
- [ ] It sets a proper og:title
If there is **featured media**:
- [ ] It adds og:image tags if it is an image (check list of attributes)
- [ ] It adds og:video tags if it is a video (check list of attributes)
